import type { Metadata } from "next";
import { Georama } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const georama = Georama({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Guilherme's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${georama.className} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" themes={["light", "dark"]} storageKey="theme">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
