import type { Metadata } from "next";
import { Georama } from "next/font/google";
import "./globals.css";

const georama = Georama({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${georama.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
